---
- name: Build rpms using mock
  block:
    - name: Build rhel {{ os_vers }} rpms locally
      command: /usr/bin/mock --root {{ mock_dir }}/rhel-{{ os_vers }}-{{ os_arch }}.cfg --resultdir {{ rpms_dir }}/{{ samba_major_version }}/rhel/{{ os_vers }}/{{ os_arch }} --rebuild {{ srpm_dir }}/{{ samba_srpm }}
      when: vendor_dist_suffix is not defined

    - name: Build rhel {{ os_vers }} rpms locally with added vendor dist
      command: /usr/bin/mock --root {{ mock_dir }}/rhel-{{ os_vers }}-{{ os_arch }}.cfg --resultdir {{ rpms_dir }}/{{ samba_major_version }}/rhel/{{ os_vers }}/{{ os_arch }} --define "vendor_dist {{ vendor_dist_suffix }}" --rebuild {{ srpm_dir }}/{{ samba_srpm }}
      when: vendor_dist_suffix is defined
  when: org_id is undefined or act_key is undefined

- name: Build rhel {{ os_vers }} rpms in a container
  when: org_id is defined and act_key is defined
  containers.podman.podman_container:
    name: "rhel_samba_build"
    image: "registry.access.redhat.com/ubi{{ os_vers }}"
    privileged: true
    command: /tmp/files/rpm-build.sh
    detach: false
    rm: true
    volume:
      - "{{ role_path }}/files:/tmp/files:z"
      - "{{ build_dir }}:{{ build_dir }}:z"
    env:
      ORG_ID: "{{ org_id }}"
      ACT_KEY: "{{ act_key }}"
      OS_VERS: "{{ os_vers }}"
      OS_ARCH: "{{ os_arch }}"
      MOCK_DIR: "{{ mock_dir }}"
      SRPM_DIR: "{{ srpm_dir }}"
      RPMS_DIR: "{{ rpms_dir }}"
      SAMBA_SRPM: "{{ samba_srpm }}"
      SAMBA_VERS: "{{ samba_major_version }}"
      VENDOR_DIST_SUFFIX: "{{ vendor_dist_suffix | default('') }}"
